### ISSUE TITLE
M9 Bayonet & Bayonet is equal for this script

### ISSUE THREAD

**Issue by antal-k** [Jack-Flux/OPSkins-Price-Checker#1]
![image](https://user-images.githubusercontent.com/15785438/41106096-910875e6-6a6f-11e8-9edb-5ae0abb52dcd.png)
![image](https://user-images.githubusercontent.com/15785438/41106113-9bff000a-6a6f-11e8-97fb-108c6b30feb2.png)

**Comment by Jack-Flux** [comment]
Should be fixed now
